spring:
  application:
    name: "gamma-async-api"
  rabbitmq:
    host: localhost
  datasource:
    url: "jdbc:mariadb://localhost:3306/requests?createDatabaseIfNotExist=true"
    username: root
    password: funnystory
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 30
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update

server.port: 8081

springdoc:
  api-docs:
    path: /swagger

queue:
  conservazione:
    requests: "conservazione-request"
    responses: "conservazione-response"
  firma:
    requests: "firma-request"
    responses: "firma-response"

logging:
  file:
    path: ./logs/