spring:
  application:
    name: "gamma-async-api-${spring.profiles.active}"
  rabbitmq:
    host: localhost
  datasource:
    url: "jdbc:mariadb://localhost:3306/requests-${spring.profiles.active}?createDatabaseIfNotExist=true"
    username: root
    password: funnystory
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 30
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update

springdoc:
  api-docs:
    path: /swagger