queue:
  request: "conservazione-request"
  response: "conservazione-response"

job:
  client:
    url: "http://localhost:8888/castlemock/mock/rest/project/khw7r3/application/oqomYj"
    path: "/conservazione"

server.port: 9091